### ISSUE TITLE
make setup removes openlane folder than complain about it

### ISSUE THREAD

**Issue by mbaykenar** [efabless/caravel_user_project#104]
I simply followed https://github.com/efabless/caravel_user_project/blob/main/docs/source/quickstart.rst

Finally I write "make setup"

Then at the stage of installing openlane it gives an error:

cd openlane && make openlane
make[1]: Entering directory '/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane'
if [ -d "/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane" ]; then\
	echo "Deleting exisiting /home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane" && \
	rm -rf /home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane && sleep 2; \
fi
Deleting exisiting /home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane
git clone https://github.com/The-OpenROAD-Project/OpenLane --branch=2022.02.23_02.50.41 --depth=1 /home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane && \
	cd /home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane && \
	export OPENLANE_IMAGE_NAME=efabless/openlane:2022.02.23_02.50.41 && \
	export IMAGE_NAME=efabless/openlane:2022.02.23_02.50.41 && \
	make pull-openlane
sh: 0: getcwd() failed: No such file or directory
Cloning into '/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane'...
fatal: Unable to read current working directory: No such file or directory
make[1]: *** [Makefile:73: openlane] Error 128
make[1]: Leaving directory '/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane'

It seems make openlane first remove openlane folder, then try to clone openlane repo tagged 2022.02.23_02.50.41 and then complain about it ? 

btw openlane repo has newer tags now

**Comment by mbaykenar** [comment]
Then I simply tried "make openlane" in root folder of the repo

This time it gives error by saying:

mkdir -p logs/tar
docker build  --rm\
	--build-arg CACHE_INVALIDATOR=1647400308\
	-t efabless/openlane:-dev\
	-f ./openlane/Dockerfile ./tar\
	| tee logs/run_base_image.build.txt
invalid argument "efabless/openlane:-dev" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make[2]: Leaving directory '/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane/docker'
make[1]: Leaving directory '/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane'

**Comment by kareefardi** [comment]
Don't set `OPENLANE_ROOT` to `caravel_user_project/openlane` which is in you case `/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane/`. Reclone and try to set it, for example, to `/home/mbaykenar/Desktop/caravel_mpw5/mystic_mpw5/openlane_src/`. We will make that clearer in future releases.

**Comment by mbaykenar** [comment]
thanks for recommendation, I will try at night and report the result, hopefully close the issue
