### ISSUE TITLE
LVS error with default user_proj_example

### ISSUE THREAD

**Issue by proppy** [efabless/caravel_user_project#105]
Running `flow.tcl` on `user_project_wrapper` with the default `user_proj_example` (counter) result in the following error:
```
LVS reports:
    net count difference = 0
    device count difference = 0
    unmatched nets = 0
    unmatched devices = 0
    unmatched pins = 2
    property failures = 0

Total errors = 2
```

## Versions

```
  magic              litex-hub/linux-64::magic-8.3.274_0_g47df9da-20220307_093930
  netgen             litex-hub/linux-64::netgen-1.5.219_0_ge11dbac-20220309_101211
  open_pdks.sky130a  litex-hub/noarch::open_pdks.sky130a-1.0.290_0_gc82996f-20220222_104027
  openroad           litex-hub/linux-64::openroad-2.0_3087_gcd06e5320-20220309_101211
```

```
OpenLane: 00da77e58c86a2fa745dafc2f4b277191cb8d3ac
caravel_user_project: afbb1601246c336b1c1e6cd87ecd85d9be8aa4d5
caravel-lite: 477c17fb986b0d3f7f3581e940095b68bd62422f
caravel_mgmt_soc_litex: 3fee299f8177cebf7919eb0e6da7f0f5ad7af31d
```

**Comment by proppy** [comment]
Also getting similar errors with `mpw-5c` tagged version:
```
OpenLane: 00da77e58c86a2fa745dafc2f4b277191cb8d3ac
caravel_user_project: b3ac77dd3737f2aa461199484538fd91c363deed mpw-5c
caravel-lite: 477c17fb986b0d3f7f3581e940095b68bd62422f mpw-5c
caravel_mgmt_soc_litex: 3fee299f8177cebf7919eb0e6da7f0f5ad7af31d mpw-5c
```
and earlier version of open_pdks and magic:
```
  magic              litex-hub/linux-64::magic-8.3.276_0_g083c0c1-20220309_101211
  open_pdks.sky130a  litex-hub/noarch::open_pdks.sky130a-1.0.284_0_g89d8afc-20220215_161633
```

**Comment by proppy** [comment]
Colab notebook that reproduce the issue:
https://gist.github.com/proppy/b15a082e39c863a01202d76cc1f1ab51
https://colab.research.google.com/gist/proppy/b15a082e39c863a01202d76cc1f1ab51/caravel-user-project-lvs-errors-105.ipynb

**Comment by d-m-bailey** [comment]
@proppy I think I responded on slack, but this occurs when there are unconnected nets with the same label in a subcircuit. If the nets are connected in the parent hierarchy, the netlists should match. At the `user_project_wrapper` level, you might check your power mesh to be sure that nothing has been orphaned.

**Comment by d-m-bailey** [comment]
With netgen 1.5.228, I do not get an error. After 1.5.228, netgen doesn't handle implicit ports correctly.

@proppy can you check that no error occurs with netgen 1.5.228?

**Comment by SaraEfabless** [comment]
Proppy, 

Can you check it with netgen 1.5.228 and let me know if its a valid issue or not?

**Comment by jeffdi** [comment]
Need to confirm if this error still exists with the current version of netgen.  @proppy

**Comment by DavidRLindley** [comment]
I'm closing this.  No response from @proppy for over two years.
