### ISSUE TITLE
RePlAce not able to place macros

### ISSUE THREAD

**Issue by aanujdu** [efabless/caravel_user_project#118]
I am trying to place two macros: a picorv32a core and a 2kB SRAM. However the Nesterov Solver never finishes placing the design and eventually errors out with the following error:
[ERROR GPL-0305] RePlAce diverged at newStepLength.

Dimensions of picorv32a: around 0.7 x 0.7 mm2
Dimensions of 2k SRAM: around 0.7 x 0.4 mm2

I set an absolute die area of 2 x 2 mm2, which I think should be good enough

I set the following macro placements:
cpu    500.000 500.000 N
RAM  500.000 1300.00  S

Please let me know if I am doing something wrong here. I also tried some other placements like
cpu      100 100 N
SRAM  100 1000 N

I have attached the reproducible as well.

Thanks,
[openroad_issue_reproducible.tar.gz](https://github.com/efabless/caravel_user_project/files/8563827/openroad_issue_reproducible.tar.gz)

**Comment by vijayank88** [comment]
set following variable in `config.tcl` and try
`set ::env(PL_BASIC_PLACEMENT) 1`

**Comment by aanujdu** [comment]
Thanks for helping @vijayank88. I actually debugged the issue to be overlapping macros, and placing them correctly removed this error. Could you please elaborate what "basic placement" means exactly and what decides when to enable or disable it? I guess we can resolve this issue after that.
