### ISSUE TITLE
Generated SRAM macros

### ISSUE THREAD

**Issue by BYCakar** [efabless/caravel_user_project#120]
Hi, I generated SRAM macros with OpenRAM, since I needed nearly 40 kB of RAM and it is almost impossible to provide it with 2 kB macros. I got Magic DRC errors and asked about it in the Slack channel. They told me that SRAM macros commonly have this issues and reccomended to turn off Magic DRC check while running user_project_wrapper. The flow passes but I have problems in precheck due to DRC issues. I also asked about it in the Slack channel and they told me that SRAM macros in the PDK directory are automatically excluded from DRC check, but they were not sure if users can add custom SRAM macros. Am I allowed to add my custom SRAM in caravel user project? If yes, how can I make the precheck tool to exclude my SRAM too?

**Comment by SaraEfabless** [comment]
The pre-check tools only recognized the published SRAM macros, so, we recommend you to use the published ones
