### ISSUE TITLE
Invalid Reference Format Error 

### ISSUE THREAD

**Issue by usmnzain** [efabless/caravel_user_project#123]
After installing pdks with `make pdk-with-volare` command and openlane with `make openlane` command, I run 
`make mount` inside the openlane directory which stops at this error. Maybe the command inside the makefile has format error since docker cannot recognize it.

`cd /merledu1/tools/openlane-mpw6/openlane && \
	docker run --rm -v /merledu1/tools/openlane-mpw6/openlane:/openlane -v /merledu1/tools/openlane-mpw6/openlane/designs:/openlane/install -v /merledu1/tools/openlane-mpw6/pdks:/merledu1/tools/openlane-mpw6/pdks -e PDK_ROOT=/merledu1/tools/openlane-mpw6/pdks -e STD_CELL_LIBRARY=sky130_fd_sc_hd --user 1000:1000 -e DISPLAY=:3 -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/merledu1/.Xauthority:/.Xauthority --network host -ti efabless/openlane:-dev
docker: invalid reference format.
See 'docker run --help'.
make: *** [Makefile:101: mount] Error 125`

I am on `mpw-6c` branch

**Comment by marwaneltoukhy** [comment]
@usmnzain Is there a specific reason why you need to run ``make mount``? This feature is not yet supported, but there's a work around, you need to add the directory which has your design in the openlane make file.
