### ISSUE TITLE
make run-precheck errors

### ISSUE THREAD

**Issue by gonsolo** [efabless/caravel_user_project#134]
I followed the documentation (two times, very closely) at

> https://github.com/efabless/caravel_user_project/blob/main/docs/source/quickstart.rst

and

> https://github.com/efabless/caravel_user_project/blob/main/docs/source/index.rst#hardening-the-user-project-using-openlane

and have the following errors:

1. make run-precheck:

> {{STEP UPDATE}} Executing Check 6 of 13: XOR
> XOR CHECK FILE NOT FOUND in /home/gonsolo/work/caravel_tutorial/caravel_gonso_project/precheck_results/21_JUN_2022___06_52_56/logs/xor_check.total
> {{XOR CHECK FAILED}} The GDS file has non-conforming geometries.

2. make xor-check

> sh /home/gonsolo/work/caravel_tutorial/caravel_gonso_project/caravel/utils/erase_box.sh gds/user_project_wrapper.gds 0 0 2920 3520
> sh: 0: cannot open /home/gonsolo/work/caravel_tutorial/caravel_gonso_project/caravel/utils/erase_box.sh: No such file
> make[1]: *** [/home/gonsolo/work/caravel_tutorial/caravel_gonso_project/caravel/Makefile:262: xor-wrapper] Error 2

3. make help

> make[1]: Verzeichnis „/home/gonsolo/work/caravel_tutorial/caravel_gonso_project/caravel“ wird betreten
> make[1]: *** [Makefile:504: help] Fehler 1

LANG=C make help works.

Any help is appreciated.

**Comment by gonsolo** [comment]
In step 3.
> git clone -b mpw-6b https://github.com/efabless/caravel_user_project caravel_example

mpw-6b is used which is obsolete as mpw-6c is available which might fix this. I think the README should be updated.

**Comment by jeffdi** [comment]
issue is resolved with the latest tag
