### ISSUE TITLE
simulation gets stuck

### ISSUE THREAD

**Issue by binoy01** [efabless/caravel_user_project#141]
Hi,
   simulation gets stuck during the power calculation phase while I tried to harden my user project. what could be the reason?

**Comment by marwaneltoukhy** [comment]
@binoy01 Can you please share a snippet of the logs?

**Comment by binoy01** [comment]
![Screenshot from 2022-07-05 12-34-55](https://user-images.githubusercontent.com/96823533/177279338-9bef9e8f-3b26-4968-ae70-4368bbc1f6fe.png)
