### ISSUE TITLE
Issue with executing resizer.tcl

### ISSUE THREAD

**Issue by binoy01** [efabless/caravel_user_project#147]
Hi,
    what could be the reason  for  'error during executing openroad script /openlane/scripts/openroad/resizer.tcl'? please check the attachment for info.
[openroad_issue_reproducible.zip](https://github.com/efabless/caravel_user_project/files/9069800/openroad_issue_reproducible.zip)

**Comment by vijayank88** [comment]
@binoy01 
Update OpenLane tag to `mpw-7a` and run the flow again. Seems you're using `mpw-5` version still

**Comment by vijayank88** [comment]
@binoy01 
Let us know if its resolve the issue.
