### ISSUE TITLE
user_defines needs to uncomment initial values

### ISSUE THREAD

**Issue by jeffdi** [efabless/caravel_user_project#165]
commented values are causing gpio_defaults to fail in tapeout

**Comment by RTimothyEdwards** [comment]
Need to swap pullup and pulldown definitions

**Comment by RTimothyEdwards** [comment]
@jeffdi :  Should this file just be including "caravel.v"?  That was the original intent.  "caravel.v" is not in this repository, though.  Will it get included properly?

**Comment by RTimothyEdwards** [comment]
Correction made which is now pull request #167 (see two comments above)
