### ISSUE TITLE
user_project_wrapper fails by default for gf180mcu

### ISSUE THREAD

**Issue by gatecat** [efabless/caravel_user_project#176]
the included `lef` for `user_proj_example` is for sky130, so running `make harden` which happens to build `user_project_wrapper` first using the old lef results in the following error:

```
[ERROR]: Last 10 lines:
[WARNING GRT-0036] Pin analog_io[3] is outside die area.
[WARNING GRT-0036] Pin analog_io[4] is outside die area.
[WARNING GRT-0036] Pin analog_io[5] is outside die area.
[WARNING GRT-0036] Pin analog_io[6] is outside die area.
[WARNING GRT-0036] Pin analog_io[7] is outside die area.
[WARNING GRT-0036] Pin analog_io[8] is outside die area.
[WARNING GRT-0036] Pin analog_io[9] is outside die area.
[ERROR GRT-0029] Pin mprj/io_in[0] does not have geometries below the max routing layer (Metal4).
Error: resizer_routing_timing.tcl, 39 GRT-0029
child process exited abnormally
```

things work fine if you manually build `user_proj_example` before `user_project_wrapper` to update the lef.

**Comment by vijayank88** [comment]
@gatecat 
Existing flow is default to sky130.
 
The order of execution is:
1. `make user_proj_example`
2. `make user_project_wrapper`

So flow automatically over-write lef/gds/def folder and you won't get such errors.

**Comment by jeffdi** [comment]
Fixed.  See issue #179.
