### ISSUE TITLE
flow fails after following instructions on clean repo

### ISSUE THREAD

**Issue by mattvenn** [efabless/caravel_user_project#2]
I followed the instructions in CARAVEL_USER.md
After 900 minutes the flow fails as Tritonroute still has ~500 violations:
here is my command history (deleted commands that are just ls, less, pwd etc)

2086     git clone git@github.com:mattvenn/caravel_user_project.git
2088     cd caravel_user_project/
2092     make install
2093     make simenv
2098     export PDK_ROOT=/home/matt/work/asic-workshop/shuttle2/pdk
2101     make pdk
2102     export CARAVEL_ROOT=$(pwd)/caravel
2109     export SIM=RTL
2115     make verify-io_ports
2120     export OPENLANE_ROOT=$(pwd)/openlane
2124     export OPENLANE_TAG=v0.12
2125     make openlane
2130     time make user_proj_example

tar.gz of user_proj_example directory after the failed run

[failed.tar.gz](https://github.com/efabless/caravel_user_project/files/6350286/failed.tar.gz)

**Comment by Manarabdelaty** [comment]
I think it could be a pdk issue, can you specify your open_pdks and skywater_pdk commits ?

**Comment by mattvenn** [comment]
I followed the instructions exactly. So the pdk and openlane are as
installed by the makefile.

**Comment by mattvenn** [comment]
I can check anyway and post tomorrow. But they were installed by the
makefile in this repo.

**Comment by mattvenn** [comment]
open_pdk: ec43817
skywater_pdk: f6f76f3
caravel_user_project: d4860ee1ca134a68dd789a13f26af27280d63ef4
openlane: 1c43d08e6a9eeb2ca2c2a36685d21179fb17149a

**Comment by Manarabdelaty** [comment]
If you clone the `mpw-two-a` tag from openlane, it will disable the pdn check for the power grid and solve the second issue. 
```
export OPENLANE_TAG=mpw-two-a
make openlane
```
But, prior to running openlane re-export the openlane tag to v0.12 because  that is the latest docker image in openlane now. 

For the first, issue the pdk commits were updated before the `mpw-two-a` tag. I think you picked the old commits before we made the update.  If you rebuild the pdk, it will install the latest of open_pdks and skywater-pdk.

**Comment by mattvenn** [comment]
I followed the new instructions.
Now it fails on building openlane:

![image](https://user-images.githubusercontent.com/634220/115743816-4dc15280-a392-11eb-8707-9cf6e487c3da.png)

looks like a Makefile issue

**Comment by Manarabdelaty** [comment]
The makefile under `<project_root>/openlane` is a symbolic link to `caravel/openlane/Makefile`, so does the `caravel/openlane/Makefile` exist ?

**Comment by mattvenn** [comment]
looks like the symlink gets made incorrectly
![image](https://user-images.githubusercontent.com/634220/115749637-962f3f00-a397-11eb-87b5-bd80029cf8c1.png)

assumes a relative path instead of absolute path for OPENLANE_ROOT?

**Comment by Manarabdelaty** [comment]
Yes, that is an issue that needs to be fixed. But, it assumes a relative path for CARAVEL_ROOT.  OPENLANE_ROOT should point to the openlane installation path not the `<project_root>/openlane` directory. 

If you have caravel as a sub-module then 
```
export CARAVEL_ROOT=caravel
make install
```
should set the symbolic links correctly.

**Comment by mattvenn** [comment]
OK, I can confirm that I get successful results in good times (less than 10 minutes).
Thanks for clearing this up.
Will you be updating the makefile to use absolute path for Caravel?
If not then I can update the readme so that it makes clear the path to Caravel must be relative.

**Comment by Manarabdelaty** [comment]
Great.  Yes, I will update the makefile.
