### ISSUE TITLE
Error in pin definition in the .def in the repository

### ISSUE THREAD

**Issue by stafverhaegen-chipflow** [efabless/caravel_user_project#209]
All the def files in caravel_user_project have error in the pin definition:
```
    - analog_io[0] + NET analog_io[0] + DIRECTION INOUT + USE SIGNAL
      + PORT
        + LAYER Metal3 ( -7200 -1120 ) ( 7200 1120 )
        + PLACED ( 6002400 2434320 ) N ;
```
The `+ PORT` line may not be there. With that line the reference def parsing code will silently ignore the pin shape and the placement.

**Comment by RTimothyEdwards** [comment]
I don't know what you mean by "may not be there".  There is definitely supposed to be a `+ PORT` line in the PIN statement according to the DEF spec.  And there are `+ PORT` statements for all the pins in the DEF files in the repository.  And what is the "reference DEF parser"?

**Comment by stafverhaegen-chipflow** [comment]
My bad. According to the [reference](http://coriolis.lip6.fr/doc/lefdef/lefdefref/lefdefref.pdf) `+ PORT` is indeed allowed and even needed for single pin with multiple  I was using a [reference](https://teamvlsi.com/2020/08/def-file-in-vlsi-design-exchange.html) before that did not mention `+ PORT` but thus is not following the standard.
With the reference implementation I mean the released code from Cadence under the Apache license downloadable from [si2.org website](https://si2.org/oa-tools-utils-libs/). It seems that if you make the PIN as PORT the def parser gives false for the `isPlaced()` and `isFixed()` methods and one has to check the ports. This we didn't do.
