### ISSUE TITLE
make run-precheck hangs at XOR check

### ISSUE THREAD

**Issue by techeraj-osh** [efabless/caravel_user_project#22]
The content of checks/xor.log while running "make run-precheck"

First Layout: /home/s2s-svr1/projects/asic/trial/caravel_user_project/checks/user_project_wrapper_empty_erased.gds
Second Layout: /home/s2s-svr1/projects/asic/trial/caravel_user_project/checks/user_project_wrapper_erased.gds
Design Name: user_project_wrapper
Output GDS will be: /home/s2s-svr1/projects/asic/trial/caravel_user_project/checks/user_project_wrapper.xor.gds
Reading /home/s2s-svr1/projects/asic/trial/caravel_user_project/checks/user_project_wrapper_empty_erased.gds ..
ERROR: In /usr/local/bin/xor_checks/xor.drc: Stream has unknown format: /home/s2s-svr1/projects/asic/trial/caravel_user_project/checks/user_project_wrapper_empty_erased.gds in Layout::read
ERROR: Stream has unknown format: /home/s2s-svr1/projects/asic/trial/caravel_user_project/checks/user_project_wrapper_empty_erased.gds in Layout::read in MacroInterpreter::execute

**Comment by techeraj-osh** [comment]
Is this issue is caused due to klayout ?

**Comment by a-omla** [comment]
@techeraj-osh  this issue is somewhat outdated, I will be closing it down, please open an issue if the problem still persists with you, thanks 🙏 .
