### ISSUE TITLE
$script_dir doesn't work in MPW8

### ISSUE THREAD

**Issue by mattvenn** [efabless/caravel_user_project#225]
I suppose it would be good to know what the plan is with tcl / json. 

I would much prefer to stay with the tcl configs, but if the plan is that they will no longer be supported then I need to get on with updating all my tools.

**Comment by kareefardi** [comment]
I don't know about the plans but you should use `$::env(DESIGN_DIR)` instead of `$script_dir`

**Comment by mattvenn** [comment]
thanks
