### ISSUE TITLE
Consistency: `deps` vs `dependencies`

### ISSUE THREAD

**Issue by xobs** [efabless/caravel_user_project#227]
In the root Makefile, the timing data is placed in a directory called `deps/`: https://github.com/efabless/caravel_user_project/blob/main/Makefile#L265

However, the documentation tells users to place dependencies under a directory called `dependencies/` by setting `OPENLANE_ROOT` and `PDK_ROOT` in https://github.com/efabless/caravel_user_project/blob/main/docs/source/index.rst#quickstart

```
export OPENLANE_ROOT=$(pwd)/dependencies/openlane_src # you need to export this whenever you start a new shell
export PDK_ROOT=$(pwd)/dependencies/pdks # you need to export this whenever you start a new shell
```

This probably should be unified to one standard -- either `dependencies/` or `deps/`.

**Comment by marwaneltoukhy** [comment]
fixed in #223
