### ISSUE TITLE
gds not found

### ISSUE THREAD

**Issue by siva12a** [efabless/caravel_user_project#24]
Hi,

The gds folder in sky130A has only decap, fakediode and fill cell gds. This is causing the following error. Do we need to copy the std cell gds to the gds folder in sky130A.

[ERROR] LEF Cell 'sky130_fd_sc_hd__a221o_4' has no matching GDS cell. Cell will be empty [ERROR] LEF Cell 'sky130_fd_sc_hd__a221o_1' has no matching GDS cell. Cell will be empty [ERROR] LEF Cell 'sky130_fd_sc_hd__a221o_2' has no matching GDS cell. Cell will be empty

**Comment by a-omla** [comment]
@siva12a I will be closing this issue as I believe it is no longer relevant to the current `caravel_user_project` or `sky130A` PDK, if you believe this is a mistake, please open a new issue, hope you understand 🙏
