### ISSUE TITLE
[ERROR DPL-0036] Detailed placement failed.

### ISSUE THREAD

**Issue by nithinkrishnanrs2023** [efabless/caravel_user_project#245]
Detailed placement failed [step 14]
[STEP 14]
[INFO]: Running Detailed Placement (log: ../home/tosil/revamped/caravel_user_project/openlane/user_proj_example/runs/23_02_02_14_11/logs/routing/14-diode_legalization.log)...
[ERROR]: during executing openroad script /openlane/scripts/openroad/dpl.tcl
[ERROR]: Log: ../home/tosil/revamped/caravel_user_project/openlane/user_proj_example/runs/23_02_02_14_11/logs/routing/14-diode_legalization.log
[ERROR]: Last 10 lines:
[INFO DPL-0035]  ANTENNA_input14_A
[issue_reproducible.zip](https://github.com/efabless/caravel_user_project/files/10567047/issue_reproducible.zip)

[INFO DPL-0035]  ANTENNA_input14_A
[INFO DPL-0035]  ANTENNA__26891__A
[INFO DPL-0035]  ANTENNA__16333__A0
[INFO DPL-0035]  ANTENNA_input1_A
[INFO DPL-0035]  ANTENNA__28920__A
[INFO DPL-0035]  ANTENNA_input2_A
[ERROR DPL-0036] Detailed placement failed.
Error: dpl.tcl, 20 DPL-0036
child process exited abnormally

[ERROR]: Creating issue reproducible...
[INFO]: Saving runtime environment...

**Comment by gagana-05** [comment]
Hello @nithinkrishnanrs2023 
Can you please lmk how did you resolve this issue?
