### ISSUE TITLE
facing issue in running cmd: make user_proj_example

### ISSUE THREAD

**Issue by gagana-05** [efabless/caravel_user_project#280]
![image](https://github.com/efabless/caravel_user_project/assets/82756709/4d42464c-772f-4408-9867-2d548cda977d)
I am running all the cmds present in order in documentation, still facing this issue

**Comment by passant5** [comment]
I think this issue is a memory issue, how much RAM do you have?

**Comment by gagana-05** [comment]
8 GB

**Comment by passant5** [comment]
Could you please attach the issue reproducible created?

**Comment by gagana-05** [comment]
I have uploaded all the files under issue_reproducible in this link, please look into it
https://drive.google.com/drive/folders/14NnJmBp1fK9o64HDjXXvg6tKiWfhl3xT?usp=sharing

**Comment by gagana-05** [comment]
I am not sure how to check that

**Comment by passant5** [comment]
run one of the following commands and check the available memory:
```
grep MemTotal /proc/meminfo
```
```
free
```

**Comment by gagana-05** [comment]
![image](https://github.com/efabless/caravel_user_project/assets/82756709/ad3e37a7-fd57-428a-a442-940978ca22a3)
Yes indeed, there is some memory limit, how can I expand this or maybe have it as unlimited

**Comment by passant5** [comment]
I am not aware of your environment. Please use google, many sources could be found for your environment specific issue
