### ISSUE TITLE
CARAVEL_LITE=0 tries to install caravel-lite but fails because no master revision

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/caravel_user_project#29]
Expecting that setting CARAVEL_LITE=0 would install the full caravel repo in the default location. Instead it crashes. 

```
[local@mpw-202106 caravel_user_project]$ echo $CARAVEL_LITE
0
[local@mpw-202106 caravel_user_project]$ make install
Installing caravel as a submodule..
Submodule 'caravel-lite' (https://github.com/efabless/caravel-lite) registered for path 'caravel'
Cloning into 'caravel'...
remote: Enumerating objects: 4720, done.
remote: Counting objects: 100% (1105/1105), done.
remote: Compressing objects: 100% (561/561), done.
remote: Total 4720 (delta 550), reused 1083 (delta 544), pack-reused 3615
Receiving objects: 100% (4720/4720), 51.46 MiB | 15.96 MiB/s, done.
Resolving deltas: 100% (2889/2889), done.
Submodule path 'caravel': checked out '13f2590e4b3a74b910dac56a6b757f5a66fd5212'
error: pathspec 'master' did not match any file(s) known to git.
make: *** [install] エラー 1
```

It appears that this is because the caravel directory already exists and the .gitmodules already contains an entry for caravel-lite to the default location.

 Can be temporarily fixed by doing the following after a clone
* Delete the relevant section from the .gitmodules file.
* Stage the .gitmodules changes `git add .gitmodules`
* Run `git rm --cached caravel` 
* Commit `git commit -m "Removed submodule "`
* Delete the now untracked submodule files `rm -rf caravel`

Specifying CARAVEL_ROOT to a non-default location may also be a work-around.

However, most likely any pulled changes will have the .gitmodules updated to include the submodule definition.

What might work is separate locations for caravel-full and caravel-lite and then switching a link according to CARAVEL_LITE.

**Comment by a-omla** [comment]
@d-m-bailey I will be closing this issue as it is not longer relevant to the current `caravel_user_project`, if you believe this is a mistake or the issue still persists, please open a new issue, hope you understand 🙏
