### ISSUE TITLE
run "make caravel-sta" error - When I get project from `git clone -b mpw-8c https://github.com/efabless/caravel_user_project`

### ISSUE THREAD

**Issue by TonyHo722** [efabless/caravel_user_project#299]
When I get project from from TAG=mpw-8c as below and found error in "make caravel-sta"
```
$ git clone -b mpw-8c https://github.com/efabless/caravel_user_project
```

# error log when run "make caravel-sta"
```
exec> read_spef -path chip_core/soc.core.RAM128 /home/tonyho/workspace/debug/d3_caravel_user_project/caravel_user_project/mgmt_core_wrapper/signoff/RAM128/openlane-signoff/spef/RAM128.nom.spef
Error: timing_top.tcl line 60, path instance 'chip_core/soc.core.RAM128' not found.
make[1]: *** [/home/tonyho/workspace/debug/d3_caravel_user_project/caravel_user_project/deps/timing-scripts/timing.mk:244: caravel-timing-typ-nom] Error 1
```

# solution - update Makefile to use `git checkout $(MPW_TAG)`
I can workaround this issue by update Makefile
```
	#( cd $(TIMING_ROOT) && git pull )
	( cd $(TIMING_ROOT) && git fetch && git checkout $(MPW_TAG); )
```
[Makefile update commit link](https://github.com/TonyHo722/caravel_user_project/commit/419e2e92ddd18040cbae5b56f8e1d2170f6a1b61)

My question is, does efabless support using mpw-8c for verify my design? or other stable tag or branch for user to verify user_project?I want to base on a stable tag or branch in https://github.com/efabless/caravel_user_project to run the tape-out flow then switch to final tape-out target in chipIgnite Shuttle (we still not decide the target).

detail issue description in [this link](https://hackmd.io/@TonyHo/BkG6cBVCh)

**Comment by marwaneltoukhy** [comment]
The main branch of `caravel_user_project` is the stable branch, and using `make setup` it will pull the stable branches of all the dependencies.
