### ISSUE TITLE
ntf-8' codec can't decode byte 0x90 in position 2: invalid start byte

### ISSUE THREAD

**Issue by Asma-Mohsin** [efabless/caravel_user_project#301]
![image](https://github.com/efabless/caravel_user_project/assets/65780913/724f09a7-a75b-4d20-b90b-24260a7aa4a3)

**Comment by marwaneltoukhy** [comment]
Are you still seeing this issue with the latest precheck update?

**Comment by Asma-Mohsin** [comment]
No. I just ran it again and the issue was fixed.
