### ISSUE TITLE
make nonnative pdk is broken for mpw-two-c

### ISSUE THREAD

**Issue by armleo** [efabless/caravel_user_project#31]
It's broken.
$(pwd) is undefined. docker fails because $(pwd) is undefined

Broken since: https://github.com/efabless/caravel_user_project/commit/d8dd010755f58e565e9fa460e4a7569d91821a42
by @Manarabdelaty

**Comment by armleo** [comment]
In other places proper shell $pdk is used

**Comment by Manarabdelaty** [comment]
Fixed by https://github.com/efabless/caravel_user_project/pull/41
