### ISSUE TITLE
cocotb counter_la test is broken

### ISSUE THREAD

**Issue by mattvenn** [efabless/caravel_user_project#314]
![image](https://github.com/efabless/caravel_user_project/assets/634220/da43ad93-42c8-4327-937c-48219a97bcc9)

having CI enabled for these tests would be great

**Comment by mattvenn** [comment]
counter_la_clk test is also broken. Only the gpio (after I fixed it) and the hello_world tests work for me. 
I checked the original tests (dv/io_ports) and they still work.

**Comment by M0stafaRady** [comment]
It seems all tests were failing because of some RTL and iverilog updates. I updated all of them at https://github.com/efabless/caravel_user_project/pull/317
