### ISSUE TITLE
Fails at io_place.py line 288 in caravel flow with simple basic counter example!!

### ISSUE THREAD

**Issue by KashifInayat** [efabless/caravel_user_project#32]
![image](https://user-images.githubusercontent.com/26200848/131076458-ed6f03e6-48c2-4f7c-810e-35b0537cf7db.png)

Please suggest a solution.

**Comment by Manarabdelaty** [comment]
Fixed by https://github.com/The-OpenROAD-Project/OpenLane/pull/609. It should work with openlane tag: `2021.09.19_20.25.16`
