### ISSUE TITLE
Link does not work anymore in the README.

### ISSUE THREAD

**Issue by manili** [efabless/caravel_user_project#36]
Hi all,
It looks like the [link](https://github.com/efabless/caravel_user_project/blob/main/docs/source/openlane/Makefile) does not work anymore in [this](https://github.com/efabless/caravel_user_project/blob/main/docs/source/index.rst) tutorial.
Thanks.

**Comment by Manarabdelaty** [comment]
Fixed by https://github.com/efabless/caravel_user_project/pull/41
