### ISSUE TITLE
make install failing

### ISSUE THREAD

**Issue by vijayank88** [efabless/caravel_user_project#43]
Hi,

I'm trying setup caravel project to my ubuntu 20.04. Used below steps but failing to complete the setup.
#git clone https://github.com/efabless/caravel_user_project.git
#cd caravel_user_project/
#make install
Installing caravel as a submodule..
The following path is ignored by one of your .gitignore files:
../caravel
Use -f if you really want to add it.
make: *** [Makefile:78: install] Error 1

How to fix this error?

**Comment by Manarabdelaty** [comment]
@vijayank88 I think you have `CARAVEL_ROOT` set to `../caravel`. In order to submodule caravel, you should export CARAVEL_ROOT as follows: 

`export CARAVEL_ROOT=$(pwd)/caravel`

Also, it is better to have `CARAVEL_ROOT` set to an absolute path because a number of targets assume that.

**Comment by vijayank88** [comment]
@Manarabdelaty thanks its got worked after re-install.
