### ISSUE TITLE
Recommended OpenLANE and SKY130 PDK Release

### ISSUE THREAD

**Issue by abdullahyildiz** [efabless/caravel_user_project#47]
We noticed that our design passes the entire flow with the versions/commit IDs

```
OPENLANE_TAG = 2021.09.19_20.25.16
SKYWATER_COMMIT = c094b6e83a4f9298e47f696ec5a7fd53535ec5eb
OPEN_PDKS_COMMIT = 6c05bc48dc88784f9d98b89d6791cdfd91526676
```

but fails during routing when the predefined versions that are defined in current caravel_user_project are used.

Is there any recommended version or commit ID for OpenLANE and SKY130 PDK to be used within Caravel Test Harness and Caravel User Project?

**Comment by vijayank88** [comment]
@abdullahyildiz 
Install OpenLane using this https://github.com/efabless/OpenLane.git git repo and point as $OPENLANE_ROOT will resolve this issue

**Comment by abdullahyildiz** [comment]
@vijayank88,

[OpenLANE Makefile](https://github.com/efabless/caravel-lite/blob/c2943440e278814787f761585b99b9ea3c1f4121/openlane/Makefile) of current Caravel User Project installs [mpw-3a](https://github.com/efabless/caravel-lite/blob/c2943440e278814787f761585b99b9ea3c1f4121/openlane/Makefile#L21) release of OpenLANE, which is also the latest commit in the repository.

Here I draw the conclusion that one should use the tag/commit IDs that comes with default Caravel User Project, not the latest ones.
