### ISSUE TITLE
precheck error

### ISSUE THREAD

**Issue by GitDiscipline** [efabless/caravel_user_project#61]
HI,
     I have encountered following  error while doing pre-check.

`GOLDEN_CARAVEL` envrionment variable is not set. Please set it to point to absolute path to the golden caravel
make: *** [Makefile:114: run-precheck] Error 1

**Comment by kop316** [comment]
Hello!

I figured out the issue: https://github.com/efabless/mpw_precheck/issues/115

As a workaround, change `CARAVEL_ROOT` to `GOLDEN_CARAVEL` here:
https://github.com/efabless/mpw_precheck/blob/mpw-5/mpw_precheck.py#L126

And it should work.
