### ISSUE TITLE
OpenLane fails when used with pre-built PDK

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel_user_project#73]
Setup:  Project is configured with PDK_ROOT pointed to a pre-installed version of the sky130 PDK from open_pdks

Problem:  When running "make user_proj_example", I get the following error:

```
[ERROR]: Failed to compare PDKs.
Could not find SOURCES file for the installed sky130A PDK.
Traceback (most recent call last):
  File "/openlane/dependencies/verify_versions.py", line 74, in verify_versions
    sources_str = open(sources_file).read()
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/pdk/sky130A/SOURCES'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/openlane/dependencies/verify_versions.py", line 77, in verify_versions
    "Could not find SOURCES file for the installed sky130A PDK."
Exception: Could not find SOURCES file for the installed sky130A PDK.

[ERROR]: Please update your environment. OpenLane will now quit.
```

The problem is that OpenLane is looking for a file called SOURCES in directory sky130A.  There is no such file created by or installed by open_pdks.  OpenLane may not just revise the PDK contents to its own liking.  The contents of SOURCES that OpenLane appears to be looking for seems to be the same information that is provided in the pdk installation's `.config/nodeinfo.json` file.  Why is that file not being used?

**Comment by donn** [comment]
eh, no good reason. can be fixed. but also, this issue is much more apt for the OpenLane repository than caravel

**Comment by RTimothyEdwards** [comment]
I wasn't sure if it was specifically related to caravel or more generally to OpenLane.  I'll re-issue it there.
