### ISSUE TITLE
make mount in openlane fails with missing tag

### ISSUE THREAD

**Issue by mattvenn** [efabless/caravel_user_project#93]
export OPENLANE_ROOT=blah
make setup
cd OPENLANE_ROOT
make mount

this fails to load the docker image because get_tag.py returns -dev instead of a correct image name.

**Comment by abdullahyildiz** [comment]
@mattvenn,

A workaround to this is to set OPENLANE_IMAGE_NAME variable and then make mount:

```
export OPENLANE_IMAGE_NAME=efabless/openlane:2021.11.23_01.42.34
make mount
```
